#ifndef _NETERR_H_
#define _NETERR_H_

enum NET_ERR
{
	NET_ERR_BASE = 1000,
	NET_NO_INIT,
	INVALID_CLIENTNO,
	INVALID_IPADDR,
	INVALID_POINTER,
	INVALID_STR_LENGTH,
	ADDR_LIST_EMPTY,
	ADDR_LIST_FULL,
	MSG_LENGTH_INVALID,
	COMM_INIT_FAILED,
	ERR_SYNC_FRAME_SEND_TIMEOUT,
	ERR_CIRCLE_BUF_READ_TIMEOUT,
	ERR_CIRCLE_BUF_GET_FAIL,
	NET_ALREADY_INIT,
	NET_THREAD_ALREADY_STARTED,
	NET_THREAD_CREATE_LOCK_FAILED,
	INVALID_HNC_MSG,

	LOCAL_FILE_OPEN_FAIL = 1200,
	NET_FILE_OPEN_FAIL,
	LOCAL_FILE_READ_FAIL,
	NET_FILE_READ_FAIL,
	NET_FILE_NOT_EXIST,
	NET_FILE_SEND_LENGTH_ERR,
	NET_FILE_SIZE_CHECK_ERR,
	NET_FILE_MD5_CHECK_ERR,
	FILE_TRAN_NOT_FINISH,
	FILE_TRAN_FILE_EMPTY,
	LOCAL_FILE_IS_EMPTY,
	NET_FILE_IS_EMPTY,

	PROG_IS_TOO_BIG,
	CIRCLE_BUF_NOT_ENOUGH_SPACE,
	USER_BUF_NOT_ENOUGH_SPACE,

	ERR_GET_EVENT_FAILED,
	ERR_GET_EVENT_TIMEOUT,

	ERR_END
};

#endif